# Generated by Django 5.0.3 on 2024-06-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourismManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='start_date',
            field=models.DateField(),
        ),
    ]
